import { Schema, Document } from 'mongoose';

export const UserSchema = new Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  hashedPassword: { type: String, required: true },
  otp: { type: Number, required: false },
  score: { type: Number, required: false },  
  otpExpiresAt: { type: Date, required: false },
  isPremium: { type: Boolean, default: false }, // 👈 ADD THIS LINE
  role: { type: String, enum: ['child', 'parent'], default: 'child' },
  parentCode: { type: String, required: false }, // Generated by child
  linkedChildId: { type: Schema.Types.ObjectId, ref: 'User', required: false },
  
});

export interface User extends Document {
  id: string;
  name: string;
  email: string;
  hashedPassword: string;
  otp?: number;
  score?: number;
  otpExpiresAt?: Date;
  isPremium: boolean; // 👈 ADD THIS LINE
  role: 'child' | 'parent';
  parentCode?: string;
  linkedChildId?: User;
}